<?php
require_once __DIR__ . '/_auth.php';
require_once dirname(__DIR__) . '/lib/property-store.php';
$owner=owner_require_login();
$rows=[];
foreach (li_all_properties() as $r) {
  if (($r['status'] ?? '') === 'OWNER_DELETED') continue;
  $ownerId=$r['owner']['account_id'] ?? null;
  $ownerMobile=$r['owner']['mobile'] ?? null;
  if (($ownerId && $ownerId === ($owner['id']??'')) || (!$ownerId && normalize_mobile((string)$ownerMobile) === normalize_mobile((string)($owner['mobile']??'')))) $rows[]=$r;
}
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>My Properties | Leads India</title><script src="https://cdn.tailwindcss.com"></script></head><body class="bg-slate-950 text-white min-h-screen"><header class="border-b border-white/10 bg-slate-950/95"><div class="max-w-5xl mx-auto px-4 py-4 flex justify-between items-center"><div><div class="font-black text-xl">LEADS <span class="text-emerald-400">INDIA</span></div><div class="text-xs text-slate-400">Property Owner Dashboard</div></div><div class="flex gap-2"><a href="/list-property" class="px-4 py-2 rounded-xl bg-emerald-600 font-bold text-sm">+ List Property</a><a href="/owner/logout.php" class="px-4 py-2 rounded-xl bg-white/10 text-sm">Logout</a></div></div></header><main class="max-w-5xl mx-auto px-4 py-8"><h1 class="text-2xl font-black">Welcome, <?=htmlspecialchars($owner['name']??'Owner')?></h1><p class="text-slate-400 text-sm mt-1">Track verification and live status of your properties.</p><?php if(isset($_GET['deleted'])): ?><div class="mt-4 p-3 rounded-xl bg-emerald-500/10 border border-emerald-500/30 text-emerald-200">Property removed from your dashboard.</div><?php endif; ?><div class="mt-6 grid gap-4"><?php if(!$rows): ?><div class="p-6 rounded-2xl bg-slate-900 border border-white/10 text-slate-400">No property submitted yet. <a class="text-emerald-400 font-bold" href="/list-property">List your first property</a>.</div><?php else: foreach($rows as $r): $p=$r['property']??[]; $ref=(string)($r['reference_id']??''); ?><div class="p-5 rounded-2xl bg-slate-900 border border-white/10"><div class="flex flex-col md:flex-row md:justify-between gap-3"><div><div class="text-xs text-slate-500 font-mono"><?=htmlspecialchars($ref)?></div><h2 class="font-bold text-lg mt-1"><?=htmlspecialchars(($p['configuration']??'Property').' • '.($p['locality']??'').' • '.($p['city']??''))?></h2><div class="text-sm text-slate-400 mt-1"><?=htmlspecialchars($p['type']??'')?> • <?=htmlspecialchars($p['area']??'')?> • ₹<?=htmlspecialchars($p['price']??'')?></div></div><div class="flex flex-col items-start md:items-end gap-2"><span class="inline-flex px-3 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/30 text-emerald-300 text-xs font-black"><?=htmlspecialchars($r['status']??'PENDING_VERIFICATION')?></span><a href="/owner/delete-property.php?reference_id=<?=rawurlencode($ref)?>" class="text-xs text-red-300 hover:text-red-200 underline">Delete Property</a></div></div><?php if(!empty($r['verification']['notes'])): ?><div class="mt-3 p-3 rounded-xl bg-amber-500/10 border border-amber-500/20 text-amber-200 text-sm">Team note: <?=htmlspecialchars((string)$r['verification']['notes'])?></div><?php endif; ?></div><?php endforeach; endif; ?></div></main></body></html>
