<?php
// Homepage property actions: Marketplace left, Free Listing right.
?>
<section id="property-actions" class="relative overflow-hidden border-b border-emerald-500/20 bg-gradient-to-br from-slate-950 via-slate-950 to-emerald-950/40">
  <div class="absolute inset-0 pointer-events-none"><div class="absolute -top-24 left-1/4 h-72 w-72 rounded-full bg-cyan-500/10 blur-3xl"></div><div class="absolute -bottom-24 right-1/4 h-72 w-72 rounded-full bg-emerald-500/10 blur-3xl"></div></div>
  <div class="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 lg:py-14">
    <div class="grid lg:grid-cols-2 gap-6 items-stretch">
      <div class="rounded-3xl border-2 border-cyan-400/60 bg-gradient-to-br from-cyan-950/60 via-slate-900 to-blue-950/50 p-6 sm:p-8 shadow-2xl shadow-cyan-500/15 backdrop-blur flex flex-col justify-between">
        <div><div class="inline-flex items-center gap-2 rounded-full border border-cyan-400/30 bg-cyan-500/10 px-3 py-1.5 text-xs font-extrabold uppercase tracking-wider text-cyan-300">🏙️ LEADS INDIA PROPERTY MARKETPLACE</div><h2 class="mt-4 text-3xl sm:text-4xl font-black tracking-tight text-white leading-tight">Find Your Perfect Property</h2><p class="mt-3 text-sm sm:text-base text-slate-300 leading-relaxed">Buy, Rent, New Launch, Commercial, Plot/Land aur Projects — smart filters ke saath Leads India marketplace explore karein.</p><div class="mt-5 grid sm:grid-cols-2 gap-3 text-xs font-semibold text-slate-300"><span class="rounded-xl border border-white/10 bg-white/5 px-3 py-2">✓ Buy / Rent / Projects</span><span class="rounded-xl border border-white/10 bg-white/5 px-3 py-2">✓ BHK & Budget Filters</span><span class="rounded-xl border border-white/10 bg-white/5 px-3 py-2">✓ Verified Live Listings</span><span class="rounded-xl border border-white/10 bg-white/5 px-3 py-2">✓ Price & Locality Insights</span></div></div>
        <a href="/properties" class="mt-7 inline-flex items-center justify-center gap-2 rounded-xl bg-cyan-400 hover:bg-cyan-300 px-6 py-4 text-sm font-black text-slate-950 shadow-xl shadow-cyan-500/20 transition">🔎 Explore Properties →</a>
      </div>
      <div class="rounded-3xl border-2 border-emerald-400/40 bg-slate-900/80 p-6 sm:p-8 shadow-2xl shadow-emerald-500/10 backdrop-blur flex flex-col justify-between">
        <div><div class="inline-flex items-center gap-2 rounded-full border border-emerald-400/30 bg-emerald-500/10 px-3 py-1.5 text-xs font-extrabold uppercase tracking-wider text-emerald-300">🏠 Property Owners • FREE</div><h2 class="mt-4 text-3xl sm:text-4xl font-black tracking-tight text-white leading-tight"><span class="text-emerald-400">FREE</span> List Your Property</h2><p class="mt-3 text-sm sm:text-base text-slate-300 leading-relaxed">Owner account banaiye, property details aur photos upload kijiye. Leads India verification ke baad approved listing marketplace par LIVE hogi.</p><div class="mt-5 grid sm:grid-cols-2 gap-3 text-xs font-semibold text-slate-300"><span class="rounded-xl border border-white/10 bg-white/5 px-3 py-2">✓ Free Account Creation</span><span class="rounded-xl border border-white/10 bg-white/5 px-3 py-2">✓ Upload Property Photos</span><span class="rounded-xl border border-white/10 bg-white/5 px-3 py-2">✓ Verification Before Live</span><span class="rounded-xl border border-white/10 bg-white/5 px-3 py-2">✓ Track Status Dashboard</span></div></div>
        <div class="mt-7 grid sm:grid-cols-2 gap-3"><a href="/owner/register.php" class="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-400 hover:bg-emerald-300 px-5 py-4 text-sm font-black text-slate-950 shadow-xl shadow-emerald-500/20 transition">FREE List Property</a><a href="/owner/login.php" class="inline-flex items-center justify-center gap-2 rounded-xl border border-white/15 bg-white/5 hover:bg-white/10 px-5 py-4 text-sm font-bold text-white transition">Owner Login</a></div>
      </div>
    </div>
  </div>
</section>
