<?php
// Homepage service actions: simple intent-led cards for Indian users.
?>
<section id="property-actions" class="relative overflow-hidden border-b border-emerald-500/20 bg-gradient-to-br from-slate-950 via-slate-950 to-emerald-950/40">
  <div class="absolute inset-0 pointer-events-none"><div class="absolute -top-24 left-1/4 h-72 w-72 rounded-full bg-cyan-500/10 blur-3xl"></div><div class="absolute -bottom-24 right-1/4 h-72 w-72 rounded-full bg-emerald-500/10 blur-3xl"></div></div>
  <div class="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 lg:py-14">
    <div class="mb-7 text-center"><div class="text-xs sm:text-sm font-black uppercase tracking-widest text-emerald-300">Aapko kya chahiye?</div><h2 class="mt-2 text-2xl sm:text-3xl font-black text-white">Ek option choose kijiye — seedha kaam shuru hoga</h2></div>
    <div class="grid lg:grid-cols-2 gap-6 items-stretch">
      <div class="rounded-3xl border-2 border-cyan-400/60 bg-gradient-to-br from-cyan-950/60 via-slate-900 to-blue-950/50 p-6 sm:p-8 shadow-2xl shadow-cyan-500/15 backdrop-blur flex flex-col justify-between">
        <div><div class="text-4xl">🏠🔍</div><div class="mt-3 inline-flex items-center rounded-full border border-cyan-400/30 bg-cyan-500/10 px-3 py-1.5 text-xs font-extrabold text-cyan-300">BUY / RENT PROPERTY</div><h3 class="mt-4 text-3xl sm:text-4xl font-black text-white leading-tight">Mujhe Property Chahiye</h3><p class="mt-3 text-sm sm:text-base text-slate-300 leading-relaxed">Flat, house, shop, office ya plot dhoondhiye. City, locality, BHK aur budget ke hisaab se search karein.</p><div class="mt-5 flex flex-wrap gap-2 text-xs font-bold text-slate-200"><span class="rounded-full bg-white/7 border border-white/10 px-3 py-2">Buy</span><span class="rounded-full bg-white/7 border border-white/10 px-3 py-2">Rent</span><span class="rounded-full bg-white/7 border border-white/10 px-3 py-2">New Projects</span><span class="rounded-full bg-white/7 border border-white/10 px-3 py-2">Commercial</span></div></div>
        <a href="/properties" class="mt-7 inline-flex items-center justify-center gap-2 rounded-2xl bg-cyan-400 hover:bg-cyan-300 px-6 py-4 text-base font-black text-slate-950 shadow-xl shadow-cyan-500/20 transition">🔎 Property Search Karein →</a>
      </div>
      <div class="rounded-3xl border-2 border-emerald-400/45 bg-gradient-to-br from-emerald-950/55 via-slate-900 to-teal-950/45 p-6 sm:p-8 shadow-2xl shadow-emerald-500/10 backdrop-blur flex flex-col justify-between">
        <div><div class="text-4xl">🏡📸</div><div class="mt-3 inline-flex items-center rounded-full border border-emerald-400/30 bg-emerald-500/10 px-3 py-1.5 text-xs font-extrabold text-emerald-300">PROPERTY OWNER • FREE LISTING</div><h3 class="mt-4 text-3xl sm:text-4xl font-black text-white leading-tight">Meri Property List Karni Hai</h3><p class="mt-3 text-sm sm:text-base text-slate-300 leading-relaxed">Sale ya rent ke liye property details aur photos upload kijiye. Verification ke baad approved listing LIVE hogi.</p><div class="mt-5 flex flex-wrap gap-2 text-xs font-bold text-slate-200"><span class="rounded-full bg-white/7 border border-white/10 px-3 py-2">Free Account</span><span class="rounded-full bg-white/7 border border-white/10 px-3 py-2">Photo Upload</span><span class="rounded-full bg-white/7 border border-white/10 px-3 py-2">Status Tracking</span></div></div>
        <div class="mt-7 grid sm:grid-cols-2 gap-3"><a href="/owner/register.php" class="inline-flex items-center justify-center rounded-2xl bg-emerald-400 hover:bg-emerald-300 px-5 py-4 text-base font-black text-slate-950 shadow-xl shadow-emerald-500/20 transition">FREE Property List Karein</a><a href="/owner/login.php" class="inline-flex items-center justify-center rounded-2xl border border-white/15 bg-white/5 hover:bg-white/10 px-5 py-4 text-sm font-bold text-white transition">Owner Login</a></div>
      </div>
      <div class="rounded-3xl border-2 border-blue-400/45 bg-gradient-to-br from-blue-950/55 via-slate-900 to-indigo-950/50 p-6 sm:p-8 shadow-2xl shadow-blue-500/10 backdrop-blur flex flex-col justify-between">
        <div><div class="text-4xl">🏦💰</div><div class="mt-3 inline-flex items-center rounded-full border border-blue-400/30 bg-blue-500/10 px-3 py-1.5 text-xs font-extrabold text-blue-300">LOAN HELP</div><h3 class="mt-4 text-3xl sm:text-4xl font-black text-white leading-tight">Mujhe Loan Chahiye</h3><p class="mt-3 text-sm sm:text-base text-slate-300 leading-relaxed">Home Loan, Personal Loan, Business Loan ya Mortgage options dekhiye. EMI aur eligibility tools bhi available hain.</p><div class="mt-5 flex flex-wrap gap-2 text-xs font-bold text-slate-200"><span class="rounded-full bg-white/7 border border-white/10 px-3 py-2">Home Loan</span><span class="rounded-full bg-white/7 border border-white/10 px-3 py-2">Business Loan</span><span class="rounded-full bg-white/7 border border-white/10 px-3 py-2">Mortgage</span><span class="rounded-full bg-white/7 border border-white/10 px-3 py-2">EMI Check</span></div></div>
        <a href="/loans" class="mt-7 inline-flex items-center justify-center gap-2 rounded-2xl bg-blue-500 hover:bg-blue-400 px-6 py-4 text-base font-black text-white shadow-xl shadow-blue-500/20 transition">💳 Loan Options Dekhein →</a>
      </div>
      <div class="rounded-3xl border-2 border-violet-400/45 bg-gradient-to-br from-violet-950/55 via-slate-900 to-fuchsia-950/40 p-6 sm:p-8 shadow-2xl shadow-violet-500/10 backdrop-blur flex flex-col justify-between">
        <div><div class="text-4xl">💻⚙️</div><div class="mt-3 inline-flex items-center rounded-full border border-violet-400/30 bg-violet-500/10 px-3 py-1.5 text-xs font-extrabold text-violet-300">SOFTWARE & AUTOMATION</div><h3 class="mt-4 text-3xl sm:text-4xl font-black text-white leading-tight">Mujhe Business Software Chahiye</h3><p class="mt-3 text-sm sm:text-base text-slate-300 leading-relaxed">CRM, automation, ready software ya custom development ke liye available solutions dekhiye.</p><div class="mt-5 flex flex-wrap gap-2 text-xs font-bold text-slate-200"><span class="rounded-full bg-white/7 border border-white/10 px-3 py-2">CRM</span><span class="rounded-full bg-white/7 border border-white/10 px-3 py-2">Automation</span><span class="rounded-full bg-white/7 border border-white/10 px-3 py-2">Ready Software</span><span class="rounded-full bg-white/7 border border-white/10 px-3 py-2">Custom Build</span></div></div>
        <a href="/software" class="mt-7 inline-flex items-center justify-center gap-2 rounded-2xl bg-violet-500 hover:bg-violet-400 px-6 py-4 text-base font-black text-white shadow-xl shadow-violet-500/20 transition">💻 Software Dekhein →</a>
      </div>
    </div>
    <div class="mt-6 text-center text-xs sm:text-sm text-slate-400">Mobile par bhi easy use • Simple navigation • Hindi/Hinglish friendly</div>
  </div>
</section>
