<?php

declare(strict_types=1);
require dirname(__DIR__) . '/lib/rainbow-social.php';
rainbow_bootstrap();
$csrf = rainbow_csrf_token();
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Rainbow Social Command Center</title>
<style>
:root{--bg:#07111f;--panel:#0d1b2c;--line:#24364c;--text:#edf5ff;--muted:#91a3b7;--ok:#34d399;--warn:#fbbf24;--bad:#fb7185}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,system-ui,sans-serif}.wrap{max-width:1200px;margin:auto;padding:24px}.top{display:flex;justify-content:space-between;gap:15px;align-items:center}.top a{color:#9ec7ff}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:18px}.panel{background:var(--panel);border:1px solid var(--line);border-radius:16px;padding:16px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:18px}.stat{background:#102238;border:1px solid var(--line);border-radius:14px;padding:14px}.stat b{display:block;font-size:24px}.muted{color:var(--muted)}input,textarea,select{width:100%;background:#091522;border:1px solid var(--line);color:#fff;border-radius:10px;padding:11px;margin:6px 0 12px}.checks{display:flex;flex-wrap:wrap;gap:10px;margin-bottom:12px}.checks label{background:#102238;padding:9px 10px;border-radius:9px}.btn{border:1px solid var(--line);background:#17304b;color:#fff;border-radius:10px;padding:10px 13px;cursor:pointer;font-weight:800}.btn.ok{background:#0d5a47}.btn.bad{background:#6b2330}.item{border-top:1px solid var(--line);padding:12px 0}.item:first-child{border-top:0}.status{font-size:12px;font-weight:800}.status.published,.status.approved,.status.scheduled{color:var(--ok)}.status.draft{color:var(--warn)}.status.failed,.status.rejected{color:var(--bad)}.actions{display:flex;gap:8px;margin-top:8px}.connectors{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.connector{background:#102238;border-radius:10px;padding:10px;font-size:13px}.small{font-size:12px}@media(max-width:800px){.grid,.stats{grid-template-columns:1fr}.connectors{grid-template-columns:1fr 1fr}.top{align-items:flex-start;flex-direction:column}}
</style></head><body><main class="wrap"><header class="top"><div><h1>Rainbow Social Command Center</h1><div class="muted">Draft → Approval → Schedule → Publish. Publishing remains locked until each official connector is configured and explicitly enabled.</div></div><a href="/rainbow-ai/">← Rainbow Commander</a></header>
<section class="stats"><div class="stat"><span class="muted">Drafts</span><b id="drafts">0</b></div><div class="stat"><span class="muted">Approved</span><b id="approved">0</b></div><div class="stat"><span class="muted">Scheduled</span><b id="scheduled">0</b></div><div class="stat"><span class="muted">Published</span><b id="published">0</b></div></section>
<div class="grid"><section class="panel"><h2>Create content draft</h2><label>Brand</label><input id="brand" maxlength="120" placeholder="YTC Education"><label>Caption / content</label><textarea id="caption" rows="7" maxlength="8000" placeholder="Write or paste approved content draft..."></textarea><label>Platforms</label><div class="checks" id="platforms"><label><input type="checkbox" value="facebook"> Facebook</label><label><input type="checkbox" value="instagram"> Instagram</label><label><input type="checkbox" value="youtube"> YouTube</label><label><input type="checkbox" value="linkedin"> LinkedIn</label><label><input type="checkbox" value="x"> X</label><label><input type="checkbox" value="google_business"> Google Business</label></div><label>Schedule (optional)</label><input id="schedule" type="datetime-local"><button class="btn" id="create">Save Draft</button><div id="msg" class="muted small" style="margin-top:10px"></div></section>
<section class="panel"><h2>Connector readiness</h2><div class="connectors" id="connectors"></div><p class="muted small">Configured does not mean publishing is enabled. External posting is intentionally disabled in this phase.</p><h2>Approval queue</h2><div id="queue" class="muted">Loading…</div></section></div></main>
<script>
const csrf=<?=json_encode($csrf,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?>;const api='/rainbow-ai/social-api.php';
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function render(d){const c=d.summary.counts||{};for(const k of ['draft','approved','scheduled','published'])document.getElementById(k==='draft'?'drafts':k).textContent=c[k]||0;const cs=d.summary.connectors||{};document.getElementById('connectors').innerHTML=Object.entries(cs).map(([k,v])=>`<div class="connector"><b>${esc(k.replace('_',' '))}</b><div class="${v.configured?'status approved':'status failed'}">${v.configured?'Configured':'Not configured'}</div><div class="muted small">Publish ${v.publish_enabled?'enabled':'locked'}</div></div>`).join('');const items=[...(d.queue||[])].reverse();document.getElementById('queue').innerHTML=items.length?items.map(x=>`<div class="item"><b>${esc(x.brand)}</b><div class="status ${esc(x.status)}">${esc(x.status)}</div><div class="small muted">${esc((x.platforms||[]).join(', '))}${x.scheduled_at?' · '+esc(x.scheduled_at):''}</div><div>${esc(x.caption).slice(0,220)}</div>${x.status==='draft'?`<div class="actions"><button class="btn ok" onclick="act('approve','${x.id}')">Approve</button><button class="btn bad" onclick="act('reject','${x.id}')">Reject</button></div>`:''}</div>`).join(''):'<div class="muted">No drafts yet.</div>'}
async function load(){const r=await fetch(api,{credentials:'same-origin',cache:'no-store'});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||'Load failed');render(d)}
async function post(body){const r=await fetch(api,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(body)});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||'Request failed');return d}
async function act(action,id){try{document.getElementById('msg').textContent='';await post({action,id});await load()}catch(e){document.getElementById('msg').textContent=e.message}}
document.getElementById('create').onclick=async()=>{const platforms=[...document.querySelectorAll('#platforms input:checked')].map(x=>x.value);const scheduled=document.getElementById('schedule').value;try{const d=await post({action:'create_draft',brand:document.getElementById('brand').value,caption:document.getElementById('caption').value,platforms,scheduled_at:scheduled});document.getElementById('caption').value='';document.getElementById('msg').textContent='Draft saved safely. Approval is required before external publishing.';render({summary:d.summary,queue:[...(await (await fetch(api,{credentials:'same-origin'})).json()).queue]})}catch(e){document.getElementById('msg').textContent=e.message}};load().catch(e=>document.getElementById('queue').textContent=e.message);
</script></body></html>